# Generated by Django 5.1.7 on 2025-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='Şəkil')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Keçid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
