# Generated by Django 5.1.7 on 2025-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(blank=True, to='MContact.user')),
            ],
            options={
                'verbose_name': 'Bildiriş',
                'verbose_name_plural': 'Bildirişlər',
            },
        ),
    ]
