# Generated by Django 5.1.7 on 2025-08-03 06:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0002_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Çatdırılma haqqı'),
        ),
    ]
