# Generated by Django 5.1.7 on 2025-03-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0003_brand_category_producttype_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='MContact.category', verbose_name='Kateqoriyalar'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Məhsul şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklənmə tarixi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MContact.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Məhsul Şəkli',
                'verbose_name_plural': 'Məhsul Şəkilləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
