# Generated by Django 5.1.7 on 2025-08-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0003_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sifariş', 'verbose_name_plural': 'Sifarişlər'},
        ),
    ]
