# Generated by Django 5.1.7 on 2025-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0004_remove_product_category_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Əsas şəkil'),
        ),
    ]
