# Generated by Django 5.1.7 on 2025-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0005_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Kateqoriya şəkli'),
        ),
    ]
