# Generated by Django 5.1.7 on 2025-08-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0005_alter_order_category_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sifariş', 'verbose_name_plural': 'Sifarişlər'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.AlterField(
            model_name='order',
            name='category_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kateqoriya Endirimi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Endirim Məbləği'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Məhsul Endirimi'),
        ),
    ]
