# Generated by Django 5.1.7 on 2025-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0006_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Müştərinin Adı və Soyadı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='customer_reviews/', verbose_name='Müştəri şəkili')),
                ('review', models.TextField(verbose_name='Müştəri rəyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Müştəri Rəyi',
                'verbose_name_plural': 'Müştəri Rəyləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
