# Generated by Django 5.1.7 on 2025-08-03 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0006_alter_order_options_remove_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerslider',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_slides', to='MContact.brand', verbose_name='Brend'),
        ),
    ]
