# Generated by Django 5.1.7 on 2025-04-12 13:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0007_customerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Bloq yazısı',
                'verbose_name_plural': 'Bloq yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
