# Generated by Django 5.1.7 on 2025-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şirkət')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='İsmarıc')),
                ('viewed', models.BooleanField(default=False, verbose_name='Baxdım')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə tarixi')),
            ],
            options={
                'verbose_name': 'Əlaqə Mesajı',
                'verbose_name_plural': 'Əlaqə Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
    ]
