# Generated by Django 5.1.7 on 2025-08-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0008_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementslide',
            options={'ordering': ['created_at'], 'verbose_name': 'Reklam slaydı', 'verbose_name_plural': 'Reklam slayderləri'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='+', to='MContact.productattributevalue', verbose_name='Xüsusiyyət dəyərləri filtri'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MContact.brand', verbose_name='Brend filtri'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MContact.category', verbose_name='Kateqoriya filtri'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maks. qiymət'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min. qiymət'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MContact.subcategory', verbose_name='Alt-kateqoriya filtri'),
        ),
        migrations.AlterField(
            model_name='advertisementslide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma'),
        ),
        migrations.AlterField(
            model_name='advertisementslide',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Xüsusi keçid'),
        ),
    ]
