# Generated by Django 5.1.7 on 2025-08-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0009_alter_advertisementslide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='+', to='MContact.productattributevalue'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MContact.brand'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MContact.category'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MContact.subcategory'),
        ),
    ]
