# Generated by Django 5.1.7 on 2025-08-06 19:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0010_homepagebanner_attribute_values_homepagebanner_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
    ]
