# Generated by Django 5.1.7 on 2025-04-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0010_contactinfo_alter_advertisementslide_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarixi')),
                ('password', models.CharField(max_length=128, verbose_name='Parol')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'İstifadəçi',
                'verbose_name_plural': 'İstifadəçilər',
            },
        ),
    ]
