# Generated by Django 5.1.7 on 2025-08-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0011_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'order', 'id'], 'verbose_name': 'Məhsul Şəkli', 'verbose_name_plural': 'Məhsul Şəkilləri'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Məhsul Versiyası', 'verbose_name_plural': 'Məhsul Versiyaları'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra nömrəsi'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra nömrəsi'),
        ),
    ]
