# Generated by Django 5.1.7 on 2025-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0013_discountcode_cart_discountcodeuse_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Səbət elementi', 'verbose_name_plural': 'Səbət'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Səbət məhsulu', 'verbose_name_plural': 'Səbət məhsulları'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'Endirim kodu', 'verbose_name_plural': 'Endirim kodları'},
        ),
        migrations.AlterModelOptions(
            name='discountcodeuse',
            options={'verbose_name': 'Endirim kodu istifadəsi', 'verbose_name_plural': 'Endirim kodu istifadələri'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sifariş', 'verbose_name_plural': 'Sifarişlər'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sifariş məhsulu', 'verbose_name_plural': 'Sifariş məhsulları'},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'İstək siyahısı elementi', 'verbose_name_plural': 'İstək siyahısı'},
        ),
    ]
