# Generated by Django 5.1.7 on 2025-06-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0017_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
