# Generated by Django 5.1.7 on 2025-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0018_remove_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sıra nömrəsi'),
        ),
    ]
