# Generated by Django 5.1.7 on 2025-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0019_alter_product_options_product_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='support_email_label',
            field=models.CharField(default='E-mail', max_length=50, verbose_name='Dəstək bölməsi E-mail etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_label',
            field=models.CharField(default='Dəstək xidməti', max_length=100, verbose_name='Dəstək bölməsi başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_mobile_label',
            field=models.CharField(default='Mobil', max_length=50, verbose_name='Dəstək bölməsi Mobil etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_email_label',
            field=models.CharField(default='E-mail', max_length=50, verbose_name='Texniki bölmə E-mail etiket'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_label',
            field=models.CharField(default='Texniki sorğular', max_length=100, verbose_name='Texniki bölmə başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_mobile_label',
            field=models.CharField(default='Mobil', max_length=50, verbose_name='Texniki bölmə Mobil etiket'),
        ),
    ]
