# Generated by Django 5.1.7 on 2025-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0021_alter_contactinfo_support_email_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='support_email_label',
            field=models.CharField(default='E-mail', max_length=50, verbose_name='Dəstək bölməsi E-mail etiketi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='support_mobile_label',
            field=models.CharField(default='Mobil', max_length=50, verbose_name='Dəstək bölməsi Mobil etiketi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='technical_email_label',
            field=models.CharField(default='E-mail', max_length=50, verbose_name='Texniki bölmə E-mail etiket'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='technical_mobile_label',
            field=models.CharField(default='Mobil', max_length=50, verbose_name='Texniki bölmə Mobil etiket'),
        ),
    ]
