# Generated by Django 5.1.7 on 2025-06-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0022_alter_contactinfo_support_email_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(verbose_name='Çatdırılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(verbose_name='Çatdırılma Vaxtı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Endirim Məbləği'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endirim Kodu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Tam Ad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Məhsul Endirimi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ara Cəm'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ümumi Məbləğ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MContact.user', verbose_name='İstifadəçi'),
        ),
    ]
