# Generated by Django 5.1.7 on 2025-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0024_alter_orderitem_options_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.PositiveIntegerField(blank=True, help_text='(İstəyə bağlı, faizlə verilir)', null=True, verbose_name='Endirim faizi'),
        ),
    ]
