# Generated by Django 5.1.7 on 2025-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0025_category_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kateqoriya Endirimi'),
        ),
    ]
