# Generated by Django 5.1.7 on 2025-06-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0026_order_category_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_logo', models.ImageField(blank=True, help_text='Yuxarıdakı navbar-da göstəriləcək logo', null=True, upload_to='logos/', verbose_name='Navbar Logo')),
            ],
            options={
                'verbose_name': 'Sayt Konfiqurasiyası',
                'verbose_name_plural': 'Sayt Konfiqurasiyaları',
            },
        ),
    ]
