# Generated by Django 5.1.7 on 2025-06-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0027_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deaktiv edilsə, məhsul səbətə əlavə oluna bilməyəcək.', verbose_name='Aktiv'),
        ),
    ]
