# Generated by Django 5.1.7 on 2025-06-17 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0028_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementslide',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='advertisementslide',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Brend adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Brend adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Brend adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriya adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriya adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriya adı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_email_label_az',
            field=models.CharField(default='E-mail', max_length=50, null=True, verbose_name='Dəstək bölməsi E-mail etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_email_label_en',
            field=models.CharField(default='E-mail', max_length=50, null=True, verbose_name='Dəstək bölməsi E-mail etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_email_label_ru',
            field=models.CharField(default='E-mail', max_length=50, null=True, verbose_name='Dəstək bölməsi E-mail etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_label_az',
            field=models.CharField(default='Dəstək xidməti', max_length=100, null=True, verbose_name='Dəstək bölməsi başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_label_en',
            field=models.CharField(default='Dəstək xidməti', max_length=100, null=True, verbose_name='Dəstək bölməsi başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_label_ru',
            field=models.CharField(default='Dəstək xidməti', max_length=100, null=True, verbose_name='Dəstək bölməsi başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_mobile_label_az',
            field=models.CharField(default='Mobil', max_length=50, null=True, verbose_name='Dəstək bölməsi Mobil etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_mobile_label_en',
            field=models.CharField(default='Mobil', max_length=50, null=True, verbose_name='Dəstək bölməsi Mobil etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='support_mobile_label_ru',
            field=models.CharField(default='Mobil', max_length=50, null=True, verbose_name='Dəstək bölməsi Mobil etiketi'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_email_label_az',
            field=models.CharField(default='E-mail', max_length=50, null=True, verbose_name='Texniki bölmə E-mail etiket'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_email_label_en',
            field=models.CharField(default='E-mail', max_length=50, null=True, verbose_name='Texniki bölmə E-mail etiket'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_email_label_ru',
            field=models.CharField(default='E-mail', max_length=50, null=True, verbose_name='Texniki bölmə E-mail etiket'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_label_az',
            field=models.CharField(default='Texniki sorğular', max_length=100, null=True, verbose_name='Texniki bölmə başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_label_en',
            field=models.CharField(default='Texniki sorğular', max_length=100, null=True, verbose_name='Texniki bölmə başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_label_ru',
            field=models.CharField(default='Texniki sorğular', max_length=100, null=True, verbose_name='Texniki bölmə başlığı'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_mobile_label_az',
            field=models.CharField(default='Mobil', max_length=50, null=True, verbose_name='Texniki bölmə Mobil etiket'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_mobile_label_en',
            field=models.CharField(default='Mobil', max_length=50, null=True, verbose_name='Texniki bölmə Mobil etiket'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='technical_mobile_label_ru',
            field=models.CharField(default='Mobil', max_length=50, null=True, verbose_name='Texniki bölmə Mobil etiket'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='full_name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Müştərinin Adı və Soyadı'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Müştərinin Adı və Soyadı'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Müştərinin Adı və Soyadı'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='review_az',
            field=models.TextField(null=True, verbose_name='Müştəri rəyi'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='review_en',
            field=models.TextField(null=True, verbose_name='Müştəri rəyi'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='review_ru',
            field=models.TextField(null=True, verbose_name='Müştəri rəyi'),
        ),
        migrations.AddField(
            model_name='partnerslider',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='partnerslider',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='partnerslider',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Məhsul adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Məhsul adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Məhsul adı'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Məhsul növü'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Məhsul növü'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Məhsul növü'),
        ),
    ]
