# Generated by Django 5.1.7 on 2025-06-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0029_advertisementslide_description_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner başlığı')),
                ('title_az', models.CharField(max_length=255, null=True, verbose_name='Banner başlığı')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Banner başlığı')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Banner başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Banner təsviri')),
                ('description_az', models.TextField(blank=True, null=True, verbose_name='Banner təsviri')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Banner təsviri')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Banner təsviri')),
                ('image', models.ImageField(upload_to='home_banners/', verbose_name='Banner şəkli')),
                ('link', models.URLField(blank=True, verbose_name='Ətraflı keçid URL-i')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Əsas səhifə – İlk reklam',
                'verbose_name_plural': 'Əsas səhifə – İlk reklam',
            },
        ),
    ]
