# Generated by Django 5.1.7 on 2025-06-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0032_alter_cartitem_unique_together_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
