# Generated by Django 5.1.7 on 2025-06-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0035_order_viewed_alter_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Xüsusiyyət adı'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Xüsusiyyət adı'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Xüsusiyyət adı'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Dəyər'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Dəyər'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Dəyər'),
        ),
    ]
