# Generated by Django 5.1.7 on 2025-06-19 19:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0038_remove_productattribute_name_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Çatdırılma haqqı'),
        ),
    ]
