# Generated by Django 5.1.7 on 2025-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0039_order_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='MContact.productattribute', verbose_name='Xüsusiyyətlər'),
        ),
    ]
