# Generated by Django 5.1.7 on 2025-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0040_remove_order_shipping_fee_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='MContact.category', verbose_name='Sub-kateqoriyalar'),
        ),
    ]
