# Generated by Django 5.1.7 on 2025-07-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0042_remove_category_subcategories_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='MContact.subcategory', verbose_name='Alt kateqoriyalar'),
        ),
    ]
