# Generated by Django 5.1.7 on 2025-07-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0044_productvariant_slug_variantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='slug',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
