# Generated by Django 5.1.7 on 2025-07-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0048_productvariantimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
    ]
