# Generated by Django 5.1.7 on 2025-07-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MContact', '0049_delete_productvariantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
